#!/bin/bash
 
DEPLOY_DIR=/home/ubuntu/apps/circle-blvd
WORK_DIR=/home/ubuntu/working/circle-blvd
mkdir -p $WORK_DIR
 
# Throw away local changes
GIT_WORK_TREE=${WORK_DIR} git checkout -f
 
# Get dependencies
cd ${WORK_DIR}/server
npm install --production
 
# Move into production, precariously
rm -r ${DEPLOY_DIR}/*
# Move dotfiles, too
shopt -s dotglob nullglob

mkdir -p ${DEPLOY_DIR}/web/public
mkdir -p ${DEPLOY_DIR}/server

mv ${WORK_DIR}/server/* ${DEPLOY_DIR}/server
mv ${WORK_DIR}/web/public/* ${DEPLOY_DIR}/web/public